### ISSUE TITLE
Null columns

### ISSUE THREAD

**Issue by mayaradaher** [ngshiheng/michelin-my-maps#87]
Hi Jerry Ng,
This latest data update has empty columns "Name", "Address", "Price", "Cuisine" and "Description". Do you have any idea when this will be fixed?

**Comment by ngshiheng** [comment]
hey Mayara! Thanks for letting me know! This issue has just been fixed. i just updated the generated data [here](https://github.com/ngshiheng/michelin-my-maps/commit/f019d2010356665de64023097d121417af769ea1) and that should be reflected on Kaggle too.
